### ISSUE TITLE
Tree limited to initial area

### ISSUE THREAD

**Issue by magnuspalmblad** [524D/compareMS2#12]
Under Windows, the tree is limited to its initial area during and after its generation. Zooming in only shows the part of the tree that fits in this rectangular area. Dragging the tree outside the area makes it disappear (though it reappears if dragging it back).

**Comment by 524D** [comment]
Zooming is no longer available due to limited support by the phylotree package. Therefore, this is no longer an issue. I will leave it open for now, hoping that zooming support will become usable again in the future.

**Comment by magnuspalmblad** [comment]
Sounds good! Let's hope they return it in the future, but it is not a critical feature for compareMS2.

**Comment by 524D** [comment]
Closed, because the status is "wontfix" without perspective to change that in the near future.
