### ISSUE TITLE
Show quality by label color

### ISSUE THREAD

**Issue by 524D** [524D/compareMS2#14]
It would be nice to see the quality of samples/matches by coloring the label. The quality could be the number of available spectra or the number of available/matched peaks.

**Comment by magnuspalmblad** [comment]
Or options:
Number of MS2 in the LC-MS/MS data
Mean or median MS2 total ion intensity

**Comment by 524D** [comment]
In the current git version, labels are colored by the quality (average number number of spectra per species/sample).
