### ISSUE TITLE
Advanced parameters that could be consider basic parameters

### ISSUE THREAD

**Issue by magnuspalmblad** [524D/compareMS2#25]
Perhaps the "Sample to species file", output filename root and output format could be consider basic I/O parameters and placed in the main tab? We can ask the beta testers what they think of course.

**Comment by 524D** [comment]
Maybe just for the "Sample to species file", though I think than we should make clear that this file is not really required to run the software.
From my point of view, the Main tab should not scare away first-time users.  
Documentation on the Nexus format all seems quite old (about 15 years), is this really a file format that anybody uses these days?

**Comment by magnuspalmblad** [comment]
Some software still reads Nexus files, but it is probably a "legacy" format these days. However, since it is stable and therefore not difficult to maintain support for, I think we can keep it. But I agree it could be in the Advanced Parameters.

There is a certain charm of having only the "select directory" and start button!

**Comment by 524D** [comment]
In that case I will leave it as is for now. We can always see if it makes sense to further divide the "advanced parameters" later on.
