### ISSUE TITLE
Supporting additional image formats?

### ISSUE THREAD

**Issue by magnuspalmblad** [524D/compareMS2#27]
The "Save picture" window currently only offer saving the phytogenetic tree in SVG format. It would be nice if compareMS2 could also export in PNG and PDF.

**Comment by 524D** [comment]
PNG is added output.
The Javascript package that outputs PDF does not produce correct output, I cannot debug that issue. SVG can be read by all major vector graphics software (e.g. Adobe Illustrator, Inkscape), so I will not spend more time on PDF output.
