### ISSUE TITLE
Latest compareMS.exe does not run in GUI

### ISSUE THREAD

**Issue by magnuspalmblad** [524D/compareMS2#31]
The current `compareMS2.exe` does not run properly in the GUI. The scan range is also returned as "undefined":
`Executing: C:\Users\nmpalmblad\Documents\compareMS2\compareMS2\external_binaries\compareMS2.exe["-A","100913.LC4.IT4.EC.S01540_1-A,8_01_1006.mgf","-B","100913.LC4.IT4.XX.S01533_1-D,8_01_1033.mgf","-R","undefined,undefined","-p",2.05,"-m",10000,"-w",1500,"-c",0.8,"-s",0.5,"-n",10,"-q",0,"-d",2,"-N",-1,"-o","H:\\Rob\\compareMS2\\2human2ecoli\\compareresult\\comparems2tmp.txt"]`

**Comment by 524D** [comment]
The scan range is now corrected in the latest git version. For the rest it works correctly for me, so if this is still an issue can you be more specific?

**Comment by magnuspalmblad** [comment]
Works fine now! I think I did something wrong installing it. The minTotalIonCurrent is not passed from the GUI, but probably should (from the "Advanced Settings").
