### ISSUE TITLE
Start scan and End scan not used in hash?

### ISSUE THREAD

**Issue by magnuspalmblad** [524D/compareMS2#32]
Changing Start scan and End scan in the GUI does not prompt a reanalysis of the files, so they must not be used for the hash. Is this correct? I am aware they are commented out in the current version of compareMS2, but eventually they will be activated.

**Comment by 524D** [comment]
I have tried it with the latest version in GitHub, but it works correctly for me. Are you sure you are using that version?

**Comment by magnuspalmblad** [comment]
Seems to work now.
