### ISSUE TITLE
Automatic generation of sample-to-species file?

### ISSUE THREAD

**Issue by magnuspalmblad** [524D/compareMS2#5]
As discussed, it may be helpful to have an option to automatically generate the sample-to-species file, with a 1-to-1 mapping between MGF filenames and the filename without the MGF. This could be the default behavior when no sample-to-species file is provided. The documentation for this function could read:

The sample-to-species file is a tab-delimited file containing the filenames in the first column and the sample type or species (in molecular phylogenetics) in the second column. Multiple filenames can map to the same species, which are then aggregated to one leaf node in the phylogenetic tree. If no file is provided, the "species" will be named after the filenames (minus the extension).

**Comment by 524D** [comment]
This is related to #6 . If compareMS2_to_distance_matrices handles the situation where the "samples_to_species" file is overcomplete or partial/completely missing, than no automatic generated "samples_to_species" file is needed.

**Comment by 524D** [comment]
The current` compare_ms2_to_distance_matrices` works correctly with incomplete/over complete or missing "samples_to_species" file. Therefore, automatic generation of that file is no longer useful.

**Comment by magnuspalmblad** [comment]
If the samples-to-species file is missing, the labels still need to be defined - e.g. by taking the filenames sans the .mgf extensions.
