### ISSUE TITLE
Windows taskbar logo appear black

### ISSUE THREAD

**Issue by magnuspalmblad** [524D/compareMS2#56]
The taskbar compareMS2 logo look all black (no reds or organges) on a transparent background:

![compareMS2_taskbar](https://github.com/user-attachments/assets/fea2e159-fa88-447d-a0b4-b7336a536e9e)

This is more than just an aesthetic issue, since it can actually be difficult to locate the icon on the taskbar.

Everywhere else, inside the software and as a regular icon in a folder or on the desktop, it look the way it should.

**Comment by 524D** [comment]
A black icon on a dark background is indeed very difficult to see. For me it looks fine however:
![image](https://github.com/user-attachments/assets/7c87cb69-b3ca-453e-b68a-7c4ea4ee946f)

I don't recall any changes in the icon lately, but just to make sure, could you check if you are using the latest release (2.1.0-beta.2)?

**Comment by magnuspalmblad** [comment]
Yes, I have 2.1.0-beta.2.

The way it looks on your computer is es expected.

**Comment by 524D** [comment]
Looks like the problem is cause by the Windows icon cache, which retained an copy from an older version. On my computer I was able to fix the problem by [erasing the icon cache](https://www.tenforums.com/tutorials/5645-rebuild-icon-cache-windows-10-a.html).

Can you please try?

**Comment by magnuspalmblad** [comment]
Yes, that fixed it! I didn't even have to restart the computer.
