### ISSUE TITLE
GUI too large for small screens

### ISSUE THREAD

**Issue by magnuspalmblad** [524D/compareMS2#8]
When using a laptop with a smaller (lower resolution) screen, the CompareMS2 window does not quite fit. It should be possible to condense the elements of the interface - perhaps by integrating the labels of the two sections in their frames and reducing the vertical spacing between the elements within each section.

**Comment by 524D** [comment]
This is solved in version v0.0.4. The settings window is now small enough to fit on all reasonable screens, and the tree window initially starts maximized and therefore always fits.
