### ISSUE TITLE
Behavior when not specfying the samples-to-species file

### ISSUE THREAD

**Issue by magnuspalmblad** [524D/compareMS2#9]
The error message when not specifying the samples-to-species file is somewhat confusing, as it complains about another text file (the one with the list of the comparison files) not being readable. Perhaps the GUI should generate a file with 1:1 mapping between filenames and filenames without the .mgf extension, and throw an error message (or display a warning) if a file is specified that is not readable (or does not exist).

**Comment by 524D** [comment]
This should be solved in version 0.0.4. Please let me know if it still generates errors.
